### ISSUE TITLE
Add support for POST calls for URLs

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/embedly-proxy#1]
We should accept URLs in a POST body as well as through GET parameters

**Comment by k88hudson** [comment]
:+1:

**Comment by k88hudson** [comment]
I'll try to limit the client sending too many URLs for now, so we don't run into this issue too often

**Comment by tspurway** [comment]
Let's make sure the NGINX logs do *not* contain the POST payloads (ie. the actual URLS)

**Comment by pdehaan** [comment]
Any ETA on when we're doing this? Is this an Alpha blocker?

**Comment by jaredkerim** [comment]
@pdehaan This is beginning now.  This and #22 will form the new /v2/extract API which should be done soon and then the client can switch to using that, hopefully before we launch any internal tests so that we're using this API from the get go.

**Comment by jaredkerim** [comment]
@tspurway The nginx access logs will not log POST bodies, nor will the gunicorn access logs.
