### ISSUE TITLE
proxy returns URL as title value

### ISSUE THREAD

**Issue by edmoz** [mozilla/embedly-proxy#133]
This is what i see in debug:

        {
          "id": 55,
          "cache_key": "trekbikes.com/us/en_US/bikes/city-bikes/c/B400",
          "places_url": "http://www.trekbikes.com/us/en_US/bikes/city-bikes/c/B400",
          "title": "http://www.trekbikes.com/us/en_US/bikes/city-bikes/c/B400",
          "type": "history",
          "description": "Trek city bikes have an agenda: make the world a happier, healthier place by getting more people on bikes more often. We make the best bikes for every purpose and every rider: smart, fun, bikes that fit the way you work, play, and live.",
          "media_url": null,
          "images": [],
          "favicons": [
            {
              "url": "http://www.trekbikes.com/_ui/desktop/theme-trek/images/favicon.ico",
              "color": [
                234,
                50,
                37
              ]
            }
          ],
          "bookmarkId": null,
          "bookmarkTitle": null,
          "bookmarkGuid": null,
          "bookmarkDateCreated": null,
          "url": "http://www.trekbikes.com/us/en_US/bikes/city-bikes/c/B400",
          "guid": "asUiRoedbHBt",
          "lastVisitDate": 1470192751014,
          "frecency": 100,
          "lastModified": null,

This is what i see when running on embedly:
http://embed.ly/docs/explore/extract?url=http%3A%2F%2Fwww.trekbikes.com%2Fus%2Fen_US%2Fbikes%2Fcity-bikes%2Fc%2FB400

titleCity bikes

**Comment by pdehaan** [comment]
This is what I see using @k88hudson's fanciful [ffmetadata](https://github.com/k88hudson/ffmetadata) tool:

![city_bikes___trek_bikes](https://cloud.githubusercontent.com/assets/557895/17379246/600f2cfc-5976-11e6-8f9f-dcfb455ac688.png)

![city_bikes___trek_bikes](https://cloud.githubusercontent.com/assets/557895/17379263/71e0d994-5976-11e6-9409-d3e17d1e3cee.png)

```json
[
  {
    "charset": "utf-8"
  },
  {
    "name": "viewport",
    "content": "width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=no, minimal-ui=yes"
  },
  {
    "name": "keywords"
  },
  {
    "name": "description"
  },
  {
    "content": "index,follow",
    "name": "robots"
  },
  {
    "name": "format-detection",
    "content": "telephone=no"
  }
]
```

**Comment by jaredkerim** [comment]
No, the urls as titles is being caused by Activity Stream, see here:

https://github.com/mozilla/activity-stream/blob/e975875984c5b3e883584e163d3819e7f020128d/content-src/components/ActivityFeed/ActivityFeed.js#L39

**Comment by edmoz** [comment]
I think what's happening is the first time metadata is requested it receives and empty value for the page since it's either taking too long / not cached.  This then sets the title = url. If you ask proxy server again at a later time, the page metadata is returned, however the title value is not updated.

**Comment by jaredkerim** [comment]
@edmoz I think you are exactly correct, and this is a bug I have been trying to track down in activity stream: https://github.com/mozilla/activity-stream/issues/971
