### ISSUE TITLE
Cut out any unused metadata fields returned by Embedly

### ISSUE THREAD

**Issue by sarracini** [mozilla/embedly-proxy#139]
There's all kinds of fields we don't need that Emedly returns to us - @jaredkerim can you post the list of fields that are necessary?

**Comment by jaredkerim** [comment]
You can remove the following fields:

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L10-L49

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L53

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L54

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L63-L66

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L68

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L69

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L74-L77

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/schema.py#L82-L84

**Comment by jaredkerim** [comment]
Remove the schemas, update the test fixture here:

https://github.com/mozilla/embedly-proxy/blob/master/embedly/embedly/tests/base.py#L9-L102

and make sure all tests are passing and that the output looks like:

    {
        url: "http://www.mozilla.org",
        original_url: "http://www.mozilla.org",
        provider_url: "http://www.mozilla.org",
        provider_name: "mozilla.com",
        provider_display: "Mozilla",
        title: "We\u2019re building a better Internet",
        description: "Did you know? Mozilla \u2014 the maker of Firefox \u2014 fights to keep the Internet a global public resource open and accessible to all.",
        favicon_url: "http://www.mozilla.org/media/img/favicon/apple-touch-icon-180x180.00050c5b754e.png",
        images: [{
          url: "https://www.mozilla.org/media/img/home/page-image.3af4522ff5e7.png",
          entropy: 1,
          height: 500,
          width: 500
        }]
      }

**Comment by pdehaan** [comment]
Ref: https://github.com/mozilla/activity-stream/issues/176
