### ISSUE TITLE
Figure out bandwidth impact of embedly proxy

### ISSUE THREAD

**Issue by oyiptong** [mozilla/embedly-proxy#14]
Embedly returns more data that content needs. We need to measure how much data that is.

If it is big, we can investigate various mitigation strategies like:

* gzip (which we probably should do anyway)
* pruning the data sent from embedly

Basically, this issue is about evaluating how much bandwidth ingress we cause the clients.
If the cost will be prohibitive, we can discuss how to make things better.

**Comment by oyiptong** [comment]
For example:

One pageload of the activity streams newtab page could generate a request about 20+ links (potentially more).
We'll want to measure how much bandwidth that will cause the browser to consume approximately.

**Comment by pdehaan** [comment]
Related: https://github.com/mozilla/activity-streams/issues/176

**Comment by jaredkerim** [comment]
Closing until a more concrete plan can be formulated.
