### ISSUE TITLE
Add request metadata to return signature

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/embedly-proxy#22]
We should add an outer layer to the response data which includes information about the request, for instance:

    {
        url_count: <int> // number urls in response
        url_data: {
            <url>: <url dict> // data from embedly about a url
        }
        error: <str> // a string which optionally contains information about what went wrong during the request
    }

@k88hudson @oyiptong @pdehaan thoughts?

**Comment by oyiptong** [comment]
`error` is optional and is only present in case of errors, correct?

**Comment by oyiptong** [comment]
`url_count` may be superfluous.

**Comment by oyiptong** [comment]
it might be valuable for dev/debug purposes, as in, for logging. We should keep it out of the server response

**Comment by pdehaan** [comment]
/cc-ing @nchapman who is our resident Embedly-whisperer.

**Comment by pdehaan** [comment]
If the JSON response has an `error` field, would we still get a `url_data` dict? Would it be empty, or could we possibly have an error and some returned data?

**Comment by jaredkerim** [comment]
@pdehaan @oyiptong I am not a fan of JSON schemas which vary, or fields which may or may not be present.  I would prefer `url_data` and `error` to always be present and simply set to `null` if not needed.  If `url_count` is unnecessary then the schema would look like

    {
        url_data: <dict>,
        error: <str>,
    }

**Comment by jaredkerim** [comment]
@pdehaan If we have an error we should get no data back and `url_data` should be `null`.
