### ISSUE TITLE
Embedly Proxy should be using HTTPS for production server

### ISSUE THREAD

**Issue by tspurway** [mozilla/embedly-proxy#27]
Adding this to track this issue for production server HTTPS / certs

**Comment by pdehaan** [comment]
Can we do this for the [dev server](http://embedly-proxy.dev.mozaws.net/extract) too? I find something mildly unsettling about forwarding my entire browsing history through the proxy over plain HTTP.

**Comment by oyiptong** [comment]
@mostlygeek what can we do to serve our dev server over https?

**Comment by mostlygeek** [comment]
Use the `*.dev.mozaws.net` TLS cert with an ELB. Point a dns name (ie: embedlyproxy.dev.mozaws.net)  at the ELB using a Route53 alias.

**Comment by pdehaan** [comment]
Bonus points if we can turn off HTTP:80 once we have HTTPS enabled everywhere. :lock:

**Comment by jaredkerim** [comment]
HTTPS has been enabled and HTTP has been disabled on the dev instance.  Closing this for now.

**Comment by oyiptong** [comment]
\o/
