### ISSUE TITLE
Promote V2 api to V1

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/embedly-proxy#43]
There's no need in alpha to preserve the V1 GET API so we should promote the V2 API to V1 rather than having a separate endpoint.

**Comment by oyiptong** [comment]
Actually, let's leave it at V2.

We'll do some minimal effort to do a fallback in the add-on first. Let's turn off V1 shortly after.

**Comment by jaredkerim** [comment]
We'll just leave this as it is for now.
