### ISSUE TITLE
Set up HSTS and HPKP for servers when HTTPS is enabled

### ISSUE THREAD

**Issue by oyiptong** [mozilla/embedly-proxy#45]
When the application is configured to run in HTTPS mode, we should enable HSTS and HPKP.

Now, since we're terminating the TLS connection at the load balancer, HTTPS mode will have to be a configuration item of the embedly proxy

**Comment by jaredkerim** [comment]
This is outside the scope of the codebase.  This will have to be filed against the production instance on bugzilla.
