### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/embedly-proxy#7]
We should be logging requests somewhere, however there are privacy considerations here because if we log an entire request that includes multiple query URLs then that can be used to reconstruct a partial window of a user's history, which we do not want.  So we should figure out what we need to log for application health and performance but that does not compromise user privacy.

**Comment by pdehaan** [comment]
Can we do full logging on the dev server and disable on production?
That may make it easier to track down when @pdehaan makes dumb queries against dev that cause HTTP >=400 errors.

**Comment by jaredkerim** [comment]
The gunicorn process should log requests to stdout.  The docker daemon can then be configured to emit those logs to the appropriate place using logging drivers.

**Comment by jaredkerim** [comment]
We are tracking nginx logs, aws stats in datadog, and stasd stats in datadog.  I think this is sufficient.

**Comment by jaredkerim** [comment]
And exceptions in sentry.
