### ISSUE TITLE
Move embedly calls to asynchronous workers

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/embedly-proxy#73]
Rather than querying embedly synchronously during a request flow, we should defer uncached URLs to a queue and have an asynchronous worker query embedly and store the results in the cache.  This will reduce overall load on the request handlers, reduce latency, and lower the likelihood of the servers being DOSed.

**Comment by oyiptong** [comment]
You could also use gevent, which would make requests async in a coroutine. You could have a pool of coroutines for each process.

**Comment by jaredkerim** [comment]
@oyiptong We are using gevent https://github.com/mozilla/embedly-proxy/blob/master/embedly/gunicorn.conf#L6 however performing the embedly query synchronously during the request flow still places an undue amount of strain on the request handlers which is causing timeouts.  Moving the calls to an async flow and only serving content out of the cache should drastically lower latency and server load.
