### ISSUE TITLE
CORS for error responses

### ISSUE THREAD

**Issue by k88hudson** [mozilla/embedly-proxy#9]
When testing this locally I ran into the issue with the query string being too long, which returns a `400 Bad Request` / `Request Line is too large` error if you `curl` it, but the client gets a `Cross-Origin Request Blocked` error instead. Maybe we want to add CORS for error responses as well?

**Comment by jaredkerim** [comment]
I think this is a small enough edge case that it's not worth worrying about right now, particularly since the V2 API should prevent this altogether.
